version: 2.1 
orbs:
   firebase-deploy: azdevs/firebase-deploy@1.0.0

workflows: 
  version: 2
  build-deploy: 
    jobs:
      - build
      - deploy:
          requires:
            - build 
          filters:
            branches:
              only: master 

jobs: 
  build:
    docker: 
      - image: circleci/node:13.12.0
    steps:
      - checkout
      - run: npx eslint test/
      - run: npm install
      - run: npm test
  deploy:
    docker: 
      - image: circleci/node:13.12.0
    steps:
      - checkout
      - run: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --only hosting
