version: 2.1
orbs:
  firebase-deploy: azdevs/firebase-deploy@1.0.0
deploy-job:
    docker:
      - image: circleci/node:13.12.0
    working_directory: ./Software-Management-2020
    steps:
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2
  deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master