version: 2.1
orbs:
  firebase-deploy: azdevs/firebase-deploy@1.0.0
jobs:
  build:
    docker:
      - image: circleci/node:13.12.0
    steps:
      - checkout
      - run: npx eslint test/
      - run: npm install
      - run: npm test
      - run: /c/Users/yakir/AppData/Roaming/npm/firebase deploy --token "$FIREBASE_TOKEN" --only hosting


